export type DefinitionStatus = 'draft' | 'in_review' | 'approved';

export interface Definition {
  id: string;
  term: string;
  definition: string;
  source: string;
  sourceUrl?: string;
  status: DefinitionStatus;
  domain: string;
  relatedTerms: string[];
  lastUpdated: string;
  author?: string;
  notes?: string;
  alternativeTerms?: string[];
}

export interface Source {
  id: string;
  name: string;
  url: string;
  termCount: number;
  lastSynced: string;
  type: 'api' | 'upload' | 'manual';
}

export const MOCK_DEFINITIONS: Definition[] = [
  // ===== FDS Begrippenkader =====
  {
    id: 'fds-1',
    term: 'Afspraak',
    definition: 'Dat wat partijen met elkaar hebben besloten.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Governance',
    relatedTerms: ['Afsprakenstelsel', 'Stelsel'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
    notes: 'Partijen zijn deelnemers aan het Federatief Datastelsel.',
  },
  {
    id: 'fds-2',
    term: 'Afsprakenstelsel',
    definition: 'Een verzameling van afspraken binnen een stelsel.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Governance',
    relatedTerms: ['Stelsel', 'Afspraak'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
    notes: 'Een afsprakenstelsel is zelf een stelsel, maar kan ook worden gezien als onderdeel van een groter stelsel.',
  },
  {
    id: 'fds-3',
    term: 'Bevoegd gezag',
    definition: 'De partij die eindverantwoordelijk is voor de dataset.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Data Governance',
    relatedTerms: ['Deelnemer', 'Partij'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
    alternativeTerms: ['Opdrachtgever'],
    notes: 'Deze partij organiseert en regelt de taken en verantwoordelijkheden van betrokken organisaties in de keten.',
  },
  {
    id: 'fds-4',
    term: 'Bronhouder',
    definition: 'De verantwoordelijke voor de inhoud en kwaliteit van een registratie die als bron is aangewezen.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Data Governance',
    relatedTerms: ['Data-aanbieder', 'Registratie', 'Bevoegd gezag'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
  },
  {
    id: 'fds-5',
    term: 'Data',
    definition: 'Vastgelegde waarnemingen of beweringen over eigenschappen van objecten.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Data Governance',
    relatedTerms: ['Dataset', 'Datadienst'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
    alternativeTerms: ['Gegevens', 'Gegeven'],
  },
  {
    id: 'fds-6',
    term: 'Data-aanbieder',
    definition: 'Een rol die data beschikbaar maakt voor data-afnemers door gegevensdiensten aan te bieden op een dataset.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Data Governance',
    relatedTerms: ['Data-afnemer', 'Datadienst', 'Deelnemer', 'Bronhouder'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
    alternativeTerms: ['Gegevensaanbieder', 'Aanbieder'],
  },
  {
    id: 'fds-7',
    term: 'Data-afnemer',
    definition: 'Een rol die data afneemt van een andere partij.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Data Governance',
    relatedTerms: ['Data-aanbieder', 'Deelnemer'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
    alternativeTerms: ['Gegevensafnemer', 'Afnemer'],
  },
  {
    id: 'fds-8',
    term: 'Data-intermediair',
    definition: 'Een rol die toegevoegde waarde levert in de keten tussen aanbieders en afnemers.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Data Governance',
    relatedTerms: ['Data-aanbieder', 'Data-afnemer'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
    notes: 'Binnen FDS wordt de intermediair niet als separate rol onderkend.',
  },
  {
    id: 'fds-9',
    term: 'Datadienst',
    definition: 'Een dienst waarmee data kunnen worden gedeeld.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Data Sharing',
    relatedTerms: ['Dataset', 'Data-aanbieder'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
    alternativeTerms: ['Gegevensdienst', 'Dataservice'],
  },
  {
    id: 'fds-10',
    term: 'Dataset',
    definition: 'Een verzameling van gegevens die als één geheel beschikbaar wordt gesteld.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Data Governance',
    relatedTerms: ['Datadienst', 'Data'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
  },
  {
    id: 'fds-11',
    term: 'Datastelsel',
    definition: 'Een stelsel voor het delen van data.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Architecture',
    relatedTerms: ['Stelsel', 'Deelnemer'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
    alternativeTerms: ['Data space', 'Dataspace', 'Gegevensruimte'],
    notes: 'Gebaseerd op gemeenschappelijke governance principes, standaarden, praktijken en ondersteunende diensten.',
  },
  {
    id: 'fds-12',
    term: 'Deelnemer',
    definition: 'Een rol van een partij die is toegelaten tot het datastelsel.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Governance',
    relatedTerms: ['Data-aanbieder', 'Data-afnemer', 'Regisseur', 'Partij'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
  },
  {
    id: 'fds-13',
    term: 'Locatie',
    definition: 'Een identificeerbare geografische plaats of benoemde plaats.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Data Governance',
    relatedTerms: [],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
  },
  {
    id: 'fds-14',
    term: 'Partij',
    definition: 'Een organisatie die juridisch bestaat.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Governance',
    relatedTerms: ['Deelnemer', 'Bevoegd gezag'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
  },
  {
    id: 'fds-15',
    term: 'Persoon',
    definition: 'Een individueel menselijk wezen dat dood of levend kan zijn maar niet denkbeeldig.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Data Governance',
    relatedTerms: [],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
    alternativeTerms: ['Natuurlijk persoon', 'Mens'],
  },
  {
    id: 'fds-16',
    term: 'Regisseur',
    definition: 'Een rol die verantwoordelijk is voor het inrichten en besturen van een datastelsel.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Governance',
    relatedTerms: ['Deelnemer', 'Datastelsel'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
  },
  {
    id: 'fds-17',
    term: 'Registratie',
    definition: 'Een gegevensverzameling waarin gegevens worden vastgelegd.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Data Governance',
    relatedTerms: ['Bronhouder', 'Sectorregistratie'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
  },
  {
    id: 'fds-18',
    term: 'Rol',
    definition: 'Een verzameling van specificerende kenmerken.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Governance',
    relatedTerms: ['Deelnemer', 'Partij'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
    notes: 'Een rol zegt iets over hoe een partij zich verhoudt tot andere partijen.',
  },
  {
    id: 'fds-19',
    term: 'Sectorregistratie',
    definition: 'Een landelijk dekkende registratie, met een wettelijke grondslag.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Data Governance',
    relatedTerms: ['Registratie'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
  },
  {
    id: 'fds-20',
    term: 'Standaard',
    definition: 'Vaststaand, erkend voorbeeld of model.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Architecture',
    relatedTerms: ['Stelsel'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
  },
  {
    id: 'fds-21',
    term: 'Stelsel',
    definition: 'Een systeem waarbinnen organisaties via afspraken, standaarden en/of voorzieningen samenwerken om bepaalde functionaliteit te realiseren.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Governance',
    relatedTerms: ['Afsprakenstelsel', 'Stelselfunctie', 'Datastelsel'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
  },
  {
    id: 'fds-22',
    term: 'Stelselfunctie',
    definition: 'Een functie die waardevol is voor de werking van het datastelsel.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Architecture',
    relatedTerms: ['Stelsel', 'Voorziening'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
  },
  {
    id: 'fds-23',
    term: 'Voorziening',
    definition: 'Een landelijk aangeboden dienst waarmee één of meer stelselfuncties worden gefaciliteerd.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'approved',
    domain: 'Architecture',
    relatedTerms: ['Stelselfunctie', 'Datadienst'],
    lastUpdated: '2026-02-16',
    author: 'Kernteam FDS',
  },

  // ===== JAGA Modellen — Gegevensdelingsbeleid =====
  {
    id: 'jaga-del-1',
    term: 'Gegevensdelingsbeleid',
    definition: 'Beleid dat de kaders stelt voor het delen van gegevens tussen organisaties, met aandacht voor privacy, beveiliging en kwaliteit.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevensdelingsbeleid/',
    status: 'approved',
    domain: 'Data Sharing',
    relatedTerms: ['Gegevensdeling', 'Gegevensleveringsprotocol'],
    lastUpdated: '2024-10-24',
    author: 'JenV CIO Raad',
  },
  {
    id: 'jaga-del-2',
    term: 'Gegevensdeling',
    definition: 'Het delen van gegevens tussen twee partijen met het oog op het gezamenlijk of individueel gebruik van die gegevens.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevensdelingsbeleid/',
    status: 'approved',
    domain: 'Data Sharing',
    relatedTerms: ['Gegevensdelingsbeleid', 'Gegevensleveringsprotocol', 'Verstrekker', 'Ontvanger'],
    lastUpdated: '2024-10-24',
    author: 'CDO Office',
    notes: 'Een gegevensdeling is een vorm van gegevensverwerking waarbij de gegevens de organisatie verlaten.',
  },
  {
    id: 'jaga-del-3',
    term: 'Gegevensleveringsprotocol',
    definition: 'Het geheel van regels en afspraken dat van toepassing is op een specifieke gegevensdeling.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevensdelingsbeleid/',
    status: 'approved',
    domain: 'Data Sharing',
    relatedTerms: ['Gegevensdeling', 'Gegevensleveringsspecificatie'],
    lastUpdated: '2024-10-24',
    author: 'CDO Office',
    alternativeTerms: ['GLP'],
  },
  {
    id: 'jaga-del-4',
    term: 'Gegevensleveringsspecificatie',
    definition: 'Specificeert de technische en semantische eigenschappen die van toepassing zijn op een gegevensdeling.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevensdelingsbeleid/',
    status: 'approved',
    domain: 'Data Sharing',
    relatedTerms: ['Gegevensdeling', 'Gegevensleveringsprotocol'],
    lastUpdated: '2024-10-24',
    author: 'CDO Office',
    alternativeTerms: ['GLS'],
  },
  {
    id: 'jaga-del-5',
    term: 'Verstrekker',
    definition: 'Een partij die gegevens in een gegevensdeling verstrekt.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevensdelingsbeleid/',
    status: 'approved',
    domain: 'Data Sharing',
    relatedTerms: ['Ontvanger', 'Gegevensdeling', 'Partij'],
    lastUpdated: '2024-10-24',
    author: 'CDO Office',
  },
  {
    id: 'jaga-del-6',
    term: 'Ontvanger',
    definition: 'Een partij aan wie gegevens in een gegevensdeling worden verstrekt.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevensdelingsbeleid/',
    status: 'approved',
    domain: 'Data Sharing',
    relatedTerms: ['Verstrekker', 'Gegevensdeling', 'Partij'],
    lastUpdated: '2024-10-24',
    author: 'CDO Office',
  },
  {
    id: 'jaga-del-7',
    term: 'Gegevensverwerking',
    definition: 'Een bewerking of een geheel van bewerkingen met betrekking tot gegevens of een geheel van gegevens.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevensdelingsbeleid/',
    status: 'approved',
    domain: 'Data Governance',
    relatedTerms: ['Gegevensdeling', 'Gegevensclassificatie'],
    lastUpdated: '2024-10-24',
    author: 'CDO Office',
  },
  {
    id: 'jaga-del-8',
    term: 'Gegevensclassificatie',
    definition: 'De systematische indeling in categorieën van de waarde van gegevens.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevensdelingsbeleid/',
    status: 'approved',
    domain: 'Data Governance',
    relatedTerms: ['Gegevensverwerking'],
    lastUpdated: '2024-10-24',
    author: 'CDO Office',
  },
  {
    id: 'jaga-del-9',
    term: 'Datamaskering',
    definition: 'Het proces waarbij gevoelige gegevens zodanig worden gewijzigd zodat ze geen of weinig waarde hebben voor ongeauthoriseerde gebruikers terwijl ze wel bruikbaar blijven.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevensdelingsbeleid/',
    status: 'approved',
    domain: 'Privacy',
    relatedTerms: ['Gegevensclassificatie', 'Persoonsgegeven'],
    lastUpdated: '2024-10-24',
    author: 'CDO Office',
  },
  {
    id: 'jaga-del-10',
    term: 'Doelbinding',
    definition: 'Geeft aan met welk doel gegevens worden gedeeld. Dit doel is vooraf bepaald, uitdrukkelijk en welomschreven.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevensdelingsbeleid/',
    status: 'approved',
    domain: 'Data Sharing',
    relatedTerms: ['Gegevensdelingsbeleid', 'Gegevensdeling'],
    lastUpdated: '2024-10-24',
    author: 'CDO Office',
  },
  {
    id: 'jaga-del-11',
    term: 'Organisatieonderdeel',
    definition: 'Een segment binnen een organisatie dat een bepaalde mate van autonomie heeft en dat zelfstandig kan opereren.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevensdelingsbeleid/',
    status: 'approved',
    domain: 'Governance',
    relatedTerms: ['Partij', 'Gegevensdeling'],
    lastUpdated: '2024-10-24',
    author: 'CDO Office',
  },

  // ===== JAGA Modellen — Gegevenskwaliteitsbeleid =====
  {
    id: 'jaga-kwal-1',
    term: 'Gegevenskwaliteitsbeleid',
    definition: 'Beleid gericht op het waarborgen van de kwaliteit van gegevens, inclusief juistheid, volledigheid, tijdigheid en consistentie.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevenskwaliteitsbeleid/',
    status: 'approved',
    domain: 'Data Quality',
    relatedTerms: ['Gegevenskwaliteit', 'Gegevenskwaliteitsdimensie', 'Gegevenskwaliteitseis'],
    lastUpdated: '2025-05-15',
    author: 'JenV CDO Raad',
  },
  {
    id: 'jaga-kwal-2',
    term: 'Gegevenskwaliteit',
    definition: 'De mate waarin een geheel van eigenschappen en kenmerken van gegevens voldoet aan eisen.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevenskwaliteitsbeleid/',
    status: 'approved',
    domain: 'Data Quality',
    relatedTerms: ['Gegevenskwaliteitsbeleid', 'Gegevenskwaliteitsmeting'],
    lastUpdated: '2025-05-15',
    author: 'CDO Office',
    alternativeTerms: ['Datakwaliteit', 'Informatiebetrouwbaarheid'],
  },
  {
    id: 'jaga-kwal-3',
    term: 'Gegevenskwaliteitsdimensie',
    definition: 'Een specifiek aspect van de kwaliteit van een gegevenselement dat bepaalt of het voldoet aan de vastgestelde eisen.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevenskwaliteitsbeleid/',
    status: 'approved',
    domain: 'Data Quality',
    relatedTerms: ['Gegevenskwaliteitsattribuut', 'Gegevenskwaliteitsbeleid'],
    lastUpdated: '2025-05-15',
    author: 'CDO Office',
    notes: 'Dimensies: Juistheid, Compleetheid, Validiteit, Consistentie, Actualiteit, Precisie, Plausibiliteit, Traceerbaarheid, Begrijpelijkheid.',
  },
  {
    id: 'jaga-kwal-4',
    term: 'Gegevenskwaliteitseis',
    definition: 'Een eis waaraan een kritiek gegevenselement moet voldoen.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevenskwaliteitsbeleid/',
    status: 'approved',
    domain: 'Data Quality',
    relatedTerms: ['Gegevenskwaliteitsbeleid', 'Kritiek gegevenselement'],
    lastUpdated: '2025-05-15',
    author: 'CDO Office',
  },
  {
    id: 'jaga-kwal-5',
    term: 'Gegevenskwaliteitsmeting',
    definition: 'Het proces van het kwantificeren en beoordelen van de gegevenskwaliteit volgens vastgestelde eisen.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevenskwaliteitsbeleid/',
    status: 'approved',
    domain: 'Data Quality',
    relatedTerms: ['Gegevenskwaliteit', 'Gegevenskwaliteitseis'],
    lastUpdated: '2025-05-15',
    author: 'CDO Office',
  },
  {
    id: 'jaga-kwal-6',
    term: 'Gegevensbron',
    definition: 'Elk systeem, gegevensmiddel, applicatie, proces dat gegevens vastlegt of produceert.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevenskwaliteitsbeleid/',
    status: 'approved',
    domain: 'Data Governance',
    relatedTerms: ['Gegevenskwaliteit', 'Registratie'],
    lastUpdated: '2025-05-15',
    author: 'CDO Office',
  },
  {
    id: 'jaga-kwal-7',
    term: 'Gegevenselement',
    definition: 'Een categorie van gegevens uit één of meerdere gegevenssets zoals verwerkt binnen een organisatorische activiteit.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevenskwaliteitsbeleid/',
    status: 'approved',
    domain: 'Data Quality',
    relatedTerms: ['Gegevenstype', 'Gegevenskwaliteitseis'],
    lastUpdated: '2025-05-15',
    author: 'CDO Office',
  },
  {
    id: 'jaga-kwal-8',
    term: 'Consistentie',
    definition: 'De mate van interne samenhang en betrouwbaarheid van gegevens, d.w.z. de mate waarin de gegevens vrij van tegenspraak zijn.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevenskwaliteitsbeleid/',
    status: 'approved',
    domain: 'Data Quality',
    relatedTerms: ['Gegevenskwaliteitsdimensie', 'Compleetheid'],
    lastUpdated: '2025-05-15',
    author: 'CDO Office',
  },
  {
    id: 'jaga-kwal-9',
    term: 'Compleetheid',
    definition: 'De mate waarin alle verwachte gegevens daadwerkelijk aanwezig zijn in een gegevensverzameling.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevenskwaliteitsbeleid/',
    status: 'approved',
    domain: 'Data Quality',
    relatedTerms: ['Gegevenskwaliteitsdimensie', 'Consistentie'],
    lastUpdated: '2025-05-15',
    author: 'CDO Office',
  },

  // ===== JAGA — DPIA =====
  {
    id: 'jaga-dpia-1',
    term: 'DPIA',
    definition: 'Data Protection Impact Assessment — een beoordeling van de impact van gegevensverwerking op de bescherming van persoonsgegevens.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/dpia/',
    status: 'approved',
    domain: 'Privacy',
    relatedTerms: ['Gegevensverwerking', 'Persoonsgegeven', 'Gegevensdelingsbeleid'],
    lastUpdated: '2025-06-01',
    author: 'CDO Office / Privacyteam CIO Rijk',
  },
  {
    id: 'jaga-dpia-2',
    term: 'Persoonsgegeven',
    definition: 'Alle informatie over een geïdentificeerde of identificeerbare natuurlijke persoon.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevensdelingsbeleid/',
    status: 'approved',
    domain: 'Privacy',
    relatedTerms: ['DPIA', 'Gegevensverwerking', 'Persoon'],
    lastUpdated: '2025-06-01',
    author: 'CDO Office',
  },

  // ===== Additional terms for interoperability =====
  {
    id: 'fds-24',
    term: 'Interoperabiliteit',
    definition: 'Het vermogen van organisaties en systemen om effectief samen te werken door gegevens te delen en te gebruiken.',
    source: 'FDS Begrippenkader',
    sourceUrl: 'https://federatief.datastelsel.nl/kennisbank/begrippen/',
    status: 'in_review',
    domain: 'Architecture',
    relatedTerms: ['Standaard', 'Stelsel', 'Datastelsel'],
    lastUpdated: '2026-02-22',
    author: 'Kernteam FDS',
  },
  {
    id: 'jaga-kwal-10',
    term: 'Gegevenscorrectie',
    definition: 'Een aanpassing van de gegevens naar aanleiding van een geconstateerd gegevenskwaliteitsprobleem.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevenskwaliteitsbeleid/',
    status: 'in_review',
    domain: 'Data Quality',
    relatedTerms: ['Gegevenskwaliteit', 'Gegevensbron'],
    lastUpdated: '2025-05-15',
    author: 'CDO Office',
  },
  {
    id: 'jaga-del-12',
    term: 'Gegevensleverset',
    definition: 'Gegevens die als één geheel worden geleverd in een gegevensdeling.',
    source: 'JAGA Modellen',
    sourceUrl: 'https://modellen.jenvgegevens.nl/gegevensdelingsbeleid/',
    status: 'draft',
    domain: 'Data Sharing',
    relatedTerms: ['Gegevensdeling', 'Gegevensleveringsspecificatie'],
    lastUpdated: '2024-10-24',
    author: 'CDO Office',
  },
];

export const MOCK_SOURCES: Source[] = [
  { id: '1', name: 'JAGA Modellen', url: 'https://modellen.jenvgegevens.nl/', termCount: 142, lastSynced: '2026-02-25', type: 'api' },
  { id: '2', name: 'FDS Begrippenkader', url: 'https://federatief.datastelsel.nl/kennisbank/begrippen/', termCount: 87, lastSynced: '2026-02-27', type: 'api' },
  { id: '3', name: 'Internal Glossary', url: '', termCount: 34, lastSynced: '2026-02-20', type: 'upload' },
];

export const DOMAINS = [
  'Data Governance',
  'Governance',
  'Data Sharing',
  'Data Quality',
  'Privacy',
  'Architecture',
];
